language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.13.0
  - jruby-head
  - rbx-3
before_script:
  - unset JRUBY_OPTS
  - unset _JAVA_OPTIONS
script: ruby -Ilib exe/rake
